config/routes.rb
Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  scope 'description' do
    mount Blacklight::Engine => '/'
    mount BlacklightDynamicSitemap::Engine => '/'

    mount Arclight::Engine => '/'

    get '/', to: 'arclight/repositories#home', as: 'home'

    root to: "arclight/repositories#index"
    concern :searchable, Blacklight::Routes::Searchable.new

    resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
      concerns :searchable
    concerns :range_searchable

    end
    devise_for :users

    concern :exportable, Blacklight::Routes::Exportable.new
    concern :hierarchy, Arclight::Routes::Hierarchy.new

    resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :hierarchy
      concerns :exportable
    end

    resources :bookmarks do
      concerns :exportable

      collection do
        delete 'clear'
        get 'clear', to: 'bookmarks#clear'
      end
    end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Render dynamic PWA files from app/views/pwa/*
    get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
    get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

    # Defines the root path route ("/")
    # root "posts#index"

    # For docker healthcheck
    get 'health', to: proc { [200, {}, ['OK']] }

    # I had to add this, as for some reason BL8.4 is sending get requests for it?
    get 'search_history/clear', to: 'search_history#clear'
  end
end

app/models/concerns/arclight/solr_document.rb
# frozen_string_literal: true

module Arclight
  ##
  # Extends Blacklight::Solr::Document to provide Arclight specific behavior
  module SolrDocument
    extend ActiveSupport::Concern

    included do
      attribute :collection_id, :string, '_root_'
      attribute :parent_ids, :array, 'parent_ids_ssim'
      attribute :legacy_parent_ids, :array, 'parent_ssim'
      Arclight.deprecation.deprecate_methods(self, legacy_parent_ids: 'Use `parent_ids` instead')
      attribute :parent_labels, :array, 'parent_unittitles_ssm'
      attribute :parent_levels, :array, 'parent_levels_ssm'
      attribute :unitid, :string, 'unitid_ssm'
      attribute :extent, :array, 'extent_ssm'
      attribute :abstract, :string, 'abstract_html_tesm'
      attribute :scope, :string, 'scopecontent_html_tesm'
      attribute :creator, :string, 'creator_ssm'
      attribute :level, :string, 'level_ssm'
      attribute :terms, :string, 'userestrict_html_tesm'
      # Restrictions for component sidebar
      attribute :parent_restrictions, :string, 'parent_access_restrict_tesm'
      # Terms for component sidebar
      attribute :parent_terms, :string, 'parent_access_terms_tesm'
      attribute :reference, :string, 'ref_ssm'
      attribute :normalized_title, :string, 'normalized_title_ssm'
      attribute :normalized_date, :string, 'normalized_date_ssm'
      attribute :total_component_count, :string, 'total_component_count_is'
      attribute :online_item_count, :string, 'online_item_count_is'
      attribute :last_indexed, :date, 'timestamp'
    end

    def repository_config
      return unless repository

      @repository_config ||= Arclight::Repository.find_by(name: repository)
    end

    def parents
      @parents ||= Arclight::Parents.from_solr_document(self).as_parents
    end

    # Get this document's EAD ID, or fall back to the collection (especially
    # for components that may not have their own.
    def eadid
      first('ead_ssi')&.strip || collection&.first('ead_ssi')&.strip
    end

    def normalized_eadid
      Arclight::NormalizedId.new(eadid).to_s
    end
    Arclight.deprecation.deprecate_methods(self, normalized_eadid: 'Use `collection_id` instead')

    def repository
      first('repository_ssm') || collection&.first('repository_ssm')
    end

    def repository_and_unitid
      [repository, unitid].compact.join(': ')
    end

    # @return [SolrDocument] a SolrDocument representing the EAD collection
    #   that this document belongs to
    def collection
      return self if collection?

      @collection ||= self.class.new(self['collection']&.dig('docs', 0), @response)
    end

    def collection_name
      collection&.normalized_title
    end

    def collection_unitid
      collection&.unitid
    end

    def abstract_or_scope
      abstract || scope
    end

    def collection_creator
      collection&.creator
    end

    def online_content?
      value = self['has_online_content_ssim']&.first
      value&.downcase.in?(['online access', 'contains online items', 'view only online content'])
    end

    def number_of_children
      first('child_component_count_isi') || 0
    end

    def children?
      number_of_children.positive?
    end

    def component_level
      first('component_level_isim')
    end

    def collection?
      level&.parameterize == 'collection'
    end

    def digital_objects
      return [] if fetch('dado_identifier_ssm', []).blank?

      [Arclight::DigitalObject.new(
        label: fetch('dado_label_tesim', []).first,
        href: fetch('dado_identifier_ssm', []).first,
        type: fetch('dado_type_ssm', []).first,
        action: fetch('dado_action_ssm', []).first,
        rights_statement: fetch('dado_rights_statement_ssim', []),
        subjects: fetch('dado_subjects_ssim', []),
        legacy_id: fetch('dado_legacy_id_ssim', []).first,
        resource_type: fetch('dado_resource_type_ssim', []).first,
        preservation_package: fetch('dado_preservation_package_ssim', []).first,
        description: fetch('dado_description_tesim', []).first,
        creator: fetch('dado_creator_ssim', []).first,
        contributor: fetch('dado_contributor_ssim', []).first,
        date_published: fetch('dado_date_published_ssm', []).first,
        thumbnail_path: fetch('thumbnail_path_ss', nil),
        replay_pdf: fetch('dado_replay_pdf_ssi', nil),
        replay_content: fetch('dado_replay_content_ss', nil)
      )]
    end

    def containers
      # NOTE: Keep uppercase characters if present, but upcase the first if not already
      containers_field = fetch('containers_ssim', []).reject(&:empty?)
      return [] if containers_field.blank?

      containers_field.map do |container|
        container.dup.sub!(/\A./, &:upcase)
      end
    end

    # @return [Array<String>] with embedded highlights using <em>...</em>
    def highlights
      highlight_field(CatalogController.blacklight_config.highlight_field)
    end

    # Factory method for constructing the Object modeling downloads
    # @return [DocumentDownloads]
    def downloads
      @downloads ||= DocumentDownloads.new(self)
    end

    def ead_file
      @ead_file ||= begin
        files = Arclight::DocumentDownloads.new(self, collection_unitid).files
        files.find do |file|
          file.type == 'ead'
        end
      end
    end

    def nest_path
      self['_nest_path_']
    end

    def root
      self['_root_'] || self['id']
    end

    def requestable?
      repository_config&.request_types&.any?
    end
  end
end

app/controllers/arclight/repositories_controller.rb
# frozen_string_literal: true

module Arclight
  # Controller for our /repositories index page
  class RepositoriesController < ApplicationController
    def index
      @repositories = Arclight::Repository.all
      load_collection_counts
    end

    def home
      @repositories = Arclight::Repository.all
      render 'home'
    end

    def show
      @repository = Arclight::Repository.find_by!(slug: params[:id])
      search_service = Blacklight.repository_class.new(blacklight_config)
      @subjects = get_subjects

      if params[:id] == "all" or params[:id] == "sub"
	      @all_response = search_service.search(
          q: "level_ssim:Collection",
          rows: 9999
        )
	      @last_response = search_service.search(
          q: "level_ssim:Collection",
          sort: "timestamp desc",
          rows: 5
        )
      else
        @all_response = search_service.search(
          q: "level_ssim:Collection repository_ssim:\"#{@repository.name}\"",
          rows: 9999
        )
	      @last_response = search_service.search(
          q: "level_ssim:Collection repository_ssim:\"#{@repository.name}\"",
          sort: "timestamp desc",
          rows: 5
        )
      end

      @all_collections = @all_response.documents
      @last_collections = @last_response.documents
      @sorted_collections = @all_collections.sort_by! {|col| col._source["title_filing_ssi"] || ""}
      @alpha_collections = {}
      @sorted_collections.each do |document|  
        if document.key?("title_filing_ssi")
          letter = document["title_filing_ssi"][0,1]
        else
          letter = ""
        end
        if @alpha_collections.key?(letter)
          @alpha_collections[letter] << document
        else
          @alpha_collections[letter] = [document]
        end
      end
    end

    private

    def subjects_list
	    subjects = Array.new
        subjects << "African Americans and Civil Rights Organizations"
        subjects << "Africana Studies"
        subjects << "Agriculture"
        subjects << "Albany, New York"
        subjects << "Anthropology"
        subjects << "Architecture"
        subjects << "Art"
        subjects << "Athletics and Sports"
        subjects << "Business and Industry"
        subjects << "Conservation and the Environment"
        subjects << "Criminal Justice and Prisons"
        subjects << "Death Penalty"
        subjects << "Economics"
        subjects << "Education"
        subjects << "Ethnic Groups"
        subjects << "Folklore"
        subjects << "Human Sexuality and Gender Identity"
        subjects << "Labor"
        subjects << "Literature"
        subjects << "Medicare"
        subjects << "Medicine and Health Care"
        subjects << "Military and Armed Conflict"
        subjects << "Music"
        subjects << "Native Americans"
        subjects << "Neighborhood and Community Associations"
        subjects << "Political Science"
        subjects << "Politics and Politicians"
        subjects << "Public Servants"
        subjects << "Radio and Television Broadcasting"
        subjects << "Railways"
        subjects << "Rensselaer County, New York"
        subjects << "Schenectady, New York"
        subjects << "Senior Citizens"
        subjects << "Social Activists and Public Advocates"
        subjects << "State University of New York SUNY, Central Administration"
        subjects << "Travel"
        subjects << "Women"
      end

    def get_subjects
    	@subjects = Array.new
      	subjects_list.each do |subject|
      	    sub = Hash.new
      	    sub["name"] = subject
                  routeScope = url_for(controller: 'repositories')
                  subjectURI = URI.join(request.base_url, File.join(routeScope, "catalog"))
                  subjectFacet = Hash.new
                  subjectFacet["f"] = {"access_subjects": [subject.gsub(" ", "+")]}
                  subjectURI.query = subjectFacet.to_query
      	    sub["uri"] = subjectURI
      	    @subjects << sub
      	end
    	@subjects
    end

    def load_collection_counts
      counts = fetch_collection_counts
      @repositories.each do |repository|
        repository.collection_count = counts[repository.name] || 0
      end
    end

    def fetch_collection_counts
      search_service = Blacklight.repository_class.new(blacklight_config)
      results = search_service.search(
        q: 'level_ssim:Collection',
        'facet.field': 'repository_ssim',
        rows: 0
      )
      counts = Hash[*results.facet_fields['repository_ssim']]
      counts["A-Z Complete List of Collections"] = results.response["numFound"]

      counts
    end
  end
end

app/views/arclight/repositories/_repository.html.erb
<div class="al-repository">
  <div class="container">
    <div class='row'>
      <div class='col-sm-4 offset-sm-4 col-md-6 offset-md-3 col-lg-4 offset-lg-0 al-repository-thumbnail hidden-md-down'>
      <%= link_to_unless(params[:id] == repository.slug, image_tag(repository.thumbnail_url, alt: repository.name, class: 'img-fluid'), arclight_engine.repository_path(repository.slug)) %>
      
      </div>

      <div class="col-sm-12 col-lg-8 al-repository-information">
        
        <div class='row no-gutters justify-content-md-center'>
            
       
          <div class="col al-repository-description" title="<%= repository.description %>">
            <h2>
              <%= link_to_unless(params[:id] == repository.slug, repository.name, arclight_engine.repository_path(repository.slug)) %>
            </h2>
            <h3 class="h6"><%= repository.tagline %></h3>
            
              <div data-arclight-truncate="true">
                <%= repository.description %>
              </div>
           
          </div>

          <% if on_repositories_index? %>
            <div class='col col-lg-2 col-sm-12 col-12 al-repository-extra hidden-md-down'>
            <%= link_to(t(:'arclight.views.repositories.view_more'), arclight_engine.repository_path(repository.slug), class: 'btn btn-primary') %>
            <div class='al-repository-extra-collection-count'>
                <% unless repository.slug == "sub" %>
                <span class="al-repository-collection-count">
                  <%= t(:'arclight.views.repositories.number_of_collections', count: repository.collection_count) %>
                </span>
                <% end %>
               </div>

         
                 </div>
          <% end %>
     
        </div>
      </div>
    </div>
  </div>
</div>

app/views/arclight/repositories/_subjects.html.erb
<% @subjects.each do |subject| %>
  <article class='al-document-title-bar document'>
	<div class='row'>
	  <div class='col-md-12'>
		<h3 class="h5">
		  <%# blacklight_icon :collection, classes: 'al-repository-content-icon' %>
		  <%= link_to subject["name"], CGI::unescape(subject["uri"].to_s) %>
		</h3>
	  </div>
	</div>
  </article>
<% end %>

app/views/arclight/repositories/_university_archives.html.erb
<% routeScope = url_for(controller: 'repositories') %>

<% officesURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% taskForcesURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% communicationsURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% financeURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% studentAffairsURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% developmentURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% academicAdminURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% schoolsURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% departmentsURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% centersURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% studentsURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% facultyURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>
<% referenceURI = URI.join(request.base_url, File.join(routeScope, "catalog")) %>

<% officesFacet = Hash.new %>
<% taskForcesFacet = Hash.new %>
<% communicationsFacet = Hash.new %>
<% financeFacet = Hash.new %>
<% studentAffairsFacet = Hash.new %>
<% developmentFacet = Hash.new %>
<% academicAdminFacet = Hash.new %>
<% schoolsFacet = Hash.new %>
<% departmentsFacet = Hash.new %>
<% centersFacet = Hash.new %>
<% studentsFacet = Hash.new %>
<% facultyFacet = Hash.new %>
<% referenceFacet = Hash.new %>

<% officesFacet["f"] = {"access_subjects": ["UAlbany+Presidential+Offices"]} %>
<% officesURI.query = officesFacet.to_query %>
<% taskForcesFacet["f"] = {"access_subjects": ["UAlbany+Task+Forces+%26+Committees"]} %>
<% taskForcesURI.query = taskForcesFacet.to_query %>
<% communicationsFacet["f"] = {"access_subjects": ["UAlbany+Communications+%26+Marketing"]} %>
<% communicationsURI.query = communicationsFacet.to_query %>
<% financeFacet["f"] = {"access_subjects": ["UAlbany+Finance+%26+Business"]} %>
<% financeURI.query = financeFacet.to_query %>
<% studentAffairsFacet["f"] = {"access_subjects": ["UAlbany+Student+Affairs"]} %>
<% studentAffairsURI.query = studentAffairsFacet.to_query %>
<% developmentFacet["f"] = {"access_subjects": ["UAlbany+University+Development"]} %>
<% developmentURI.query = developmentFacet.to_query %>
<% academicAdminFacet["f"] = {"access_subjects": ["UAlbany+Academic+Administration"]} %>
<% academicAdminURI.query = academicAdminFacet.to_query %>
<% schoolsFacet["f"] = {"access_subjects": ["UAlbany+Schools+%26+Colleges"]} %>
<% schoolsURI.query = schoolsFacet.to_query %>
<% departmentsFacet["f"] = {"access_subjects": ["UAlbany+Academic+Departments"]} %>
<% departmentsURI.query = departmentsFacet.to_query %>
<% centersFacet["f"] = {"access_subjects": ["UAlbany+Centers+%26+Institutes"]} %>
<% centersURI.query = centersFacet.to_query %>
<% studentsFacet["f"] = {"access_subjects": ["UAlbany+Student+Groups"]} %>
<% studentsURI.query = studentsFacet.to_query %>
<% facultyFacet["f"] = {"access_subjects": ["UAlbany+Faculty+%26+Alumni Papers"]} %>
<% facultyURI.query = facultyFacet.to_query %>
<% referenceFacet["f"] = {"access_subjects": ["UAlbany+Reference+Collections"]} %>
<% referenceURI.query = referenceFacet.to_query %>

<ul class="ua_browse_list">
	<div class="category"><li>University Leadership</li></div>
	<ul>
		<li><%= link_to "Office of the President", solr_document_path("ua000") %></li>
		<li><%= link_to "University Council", solr_document_path("ua100") %></li>
		<li><%= link_to "University Senate", solr_document_path("ua200") %></li>
		<li><%= link_to "Presidential Offices", CGI::unescape(officesURI.to_s) %></li>
		<li><%= link_to "Task Forces & Committees", CGI::unescape(taskForcesURI.to_s) %></li>
	</ul>
	
	<div class="category"><li>Administative Units</li></div>
	<ul>
		<li><%= link_to "Athletics", solr_document_path("ua746") %></li>
		<li><%= link_to "Communications & Marketing", CGI::unescape(communicationsURI.to_s) %></li>
		<li><%= link_to "Diversity & Inclusion", solr_document_path("ua370") %></li>
		<li><%= link_to "Finance & Business", CGI::unescape(financeURI.to_s) %></li>
		<li><%= link_to "Information Systems and Technology", solr_document_path("ua535") %></li>
		<li><%= link_to "Student Affairs", CGI::unescape(studentAffairsURI.to_s) %></li>
		<li><%= link_to "University Foundation, Alumni, and Fundraising", CGI::unescape(developmentURI.to_s) %></li>
	</ul>
	
	<div class="category"><li>Academic Affairs</li></div>
	<ul>
		<li><%= link_to "Office of the Provost", solr_document_path("ua500") %></li>
		<li><%= link_to "Academic Administation", CGI::unescape(academicAdminURI.to_s) %></li>
		<li><%= link_to "Schools & Colleges", CGI::unescape(schoolsURI.to_s) %></li>
		<li><%= link_to "Academic Departments", CGI::unescape(departmentsURI.to_s) %></li>
	</ul>
	
	<div class="category"><li><%= link_to "Centers & Institutes", CGI::unescape(centersURI.to_s) %></li></div>
	<div class="category"><li><%= link_to "Student Groups", CGI::unescape(studentsURI.to_s) %></li></div>
	<div class="category"><li><%= link_to "Faculty & Alumni Papers", CGI::unescape(facultyURI.to_s) %></li></div>
	<div class="category"><li><%= link_to "Reference Collections", CGI::unescape(referenceURI.to_s) %></li></div>
	<div class="category"><li><%= link_to "Web Archives", "https://archives.albany.edu/web/webarchives" %></li></div>
	
</ul>

app/views/arclight/repositories/home.html.erb
<% breadcrumb :repositories %>
<div class="col-lg-8 offset-lg-2">

	<!--<h1 class="sr-only visually-hidden"><%= t('arclight.views.home.title') %></h1>-->

	<div class="al-repositories">
		<% @page_title = t(:'arclight.views.home.title') %>
		<%# render 'shared/breadcrumbs' %>

		<div class="card">
			<div class="card-body">
			   <h1 class="h2">About the Collections</h1>
			   
			   <p>
				We collect, preserve, and make available unique archives and manuscript collections, the official records of the university, and rare and specialized book collections. Learn more about our <a href="<%= request.base_url + "/web/mission" %>">Mission & Purpose</a>.
			   </p>
			   
			   <ul class="ua_browse_list about_collections">
			   		<%# routeScope = url_for(controller: 'repositories') %>
			   		<%# raise routeScope.inspect %>
					<div class="category row">
						<div class="col-md 12 col-xl-8">
						<li><a href="<%= request.base_url + "/description/repositories" %>">Archives & Manuscripts</a></li>
						<p>These collections contain material created by individuals or are the permanent records of an organization or business.</p>
						<p>They are divided into five major collecting areas:</p>
					<ul>
						<li><a href="<%= request.base_url + "/description/repositories/apap" %>">New York State Modern Political Archive</a></li>
							<ul>
								<li>Elected officials, interest groups, and activists from New York State</li>
							</ul>
						<li><a href="<%= request.base_url + "/description/repositories/ndpa" %>">National Death Penalty Archive</a></li>
							<ul>
								<li>Researchers, writers, activists, and records on capital punishment in the United States</li>
							</ul>
						<li><a href="<%= request.base_url + "/description/repositories/ger" %>">German and Jewish Intellectual Émigré Collections</a></li>
							<ul>
								<li>Papers of German-speaking intellectuals who fled the Nazi regime in the 1930s</li>
							</ul>
						<li><a href="<%= request.base_url + "/description/repositories/ua" %>">University Archives</a></li>
							<ul>
								<li>The official permanent records of the University at Albany, SUNY and its predecessor schools</li>
							</ul>
						<li><a href="<%= request.base_url + "/description/repositories/mss" %>">Business and Literary Manuscripts</a></li>
							<ul>
								<li>Manuscripts, records, and papers primarily related to businesses and people of New York and New England</li>
							</ul>
					</ul>
					</div>
					<div class="col-md-11 offset-md-1 col-xl-4 offset-xl-0">
						<div class="alert alert-info mt-2" role="alert">
							<a data-bs-toggle="collapse" href="#collapseAbout" role="button" aria-expanded="false" aria-controls="collapseAbout">
								<h2 class="alert-heading h6 mb-0">
								<i class="fa fa-info-circle" aria-hidden="true"></i>
								About Archives & Manuscripts
								<i class="fa fa-angle-down rotate-icon pull-right"></i>
								</h2>
							</a>
							<div class="collapse" id="collapseAbout">
								<hr/>
								<p>
									Archives & Manuscripts are groupings of physical and digital records that are not available anyplace else and document a key topic for potential research. Each letter, film reel, or spreadsheet only tells part of the story, so we try and keep these collections grouped together so you can see how their creators used them. Items that are used often may be described individually, but other collections can be hundreds of boxes and might only be described as a large group.</p>
								<p>
									Generally, "manuscripts" are created by individual people and "archives" are the accumulated permanent records of an organization or business, but these terms are often mixed. Collections are usually described as either "Papers," created by an individual person, "Records," the official documents of an organization, or as a "Collection" gathered from a number of original sources on a common subject or topic. 
								</p>
							</div>
						</div>
					</div>
					</div>
					<div class="category">
						<li><a href="<%= request.base_url + "/books/?f[collecting_area_ssim][]=Mathes+Childrens+Literature" %>">Miriam Snow Mathes Historical Children's Literature Collection</a></li>
						<p>
							Designed to provide access to out-of-print children's literature, the Mathes Collection includes books and periodicals for children and young adults, published in the United States, mostly between 1875 and 1960.
						</p>
					</div>
					
					<div class="category">
						<li><a href="<%= request.base_url + "/books/?f[collecting_area_ssim][]=Political+Pamphlets" %>">Political Pamphlets</a></li>
						<p>
							This is an artificial collection of thousands of rare pamphlets published on a wide variety of 20th century political topics.
						</p>
					</div>
					
					<div class="category">
						<li><a href="<%= request.base_url + "/books" %> ">Rare Books</a></li>
						<p>
							A large collection of unique and specialized books that do not circulate because of the item's uniqueness, fragility, or scarcity.
						</p>
					</div>
				
				</ul>
			</div>
		</div>
	</div>

</div>

app/views/arclight/repositories/index.html.erb
<% breadcrumb :repositories %>
<div class="col-lg-9 offset-lg-3">

  <div class="al-repositories">
    <% @page_title = t('arclight.views.repositories.title') %>
    <%= render 'shared/breadcrumbs' %>
    <div class="card al-repository">
      <div class="card-body">
        <div class="card-title">
          <h1 class="h3"><%= t('arclight.repositories') %></h1>
        </div>
        <div class="h6 text-muted">Collecting Areas</div>
        <p class="">
          Archives or manuscript collections are sets of original, unpublished materials that are preserved within context of how they were created or used and divided into five major collecting areas.
        </p>
      </div>
    </div>
    <%= render @repositories %>
  </div>
</div>

app/views/arclight/repositories/show.html.erb
<% @page_title = t(:'arclight.views.repositories.show', name: @repository.name) %>
<% breadcrumb :repository, @repository %>
<%= render 'shared/breadcrumbs' %>
<%= render @repository %>

<h1 class="sr-only visually-hidden"><%= t(:'arclight.views.repositories.show', name: @repository.name) %></h1>

<% content_for(:sidebar) do %>
 <div class="row alpha-menu sticky-top">
    <% unless @repository.slug == "ua" or @repository.slug == "sub" %>
      <div class="col-md-12">
        <section class="sidebar-scroll-wrapper">
          <ul class="list-group">
            <a href="#" class="list-group-item list-group-item-action"><%= @repository.name %></a>
            <% @alpha_collections.keys.each do |letter| %>
              <a href="#<%= letter %>" class="list-group-item list-group-item-action"><%= letter %></a>
            <% end %>
          </ul>
        </section>
      <div>
    <% end %>
  </div>
<% end %>



<div class="row">
  <div id="documents" class="col-md-8 <%= 'full-collections' unless @repository.slug == 'ua' || @repository.slug == 'sub' %>">

  <div class="card">
	<div class="card-body">
	   <h2 class="h4"> <%= @repository.name %> Collections </h2>

	<% if @repository.slug == "ua" %>
		<%= render partial: 'university_archives' %>
  <% elsif @repository.slug == "sub" %>
    <%= render partial: 'subjects' %>
	<% else %>
    
    <% @alpha_collections.keys.each do |letter| %>
      <div id="<%= letter %>" class="col-md-12">
        <% @alpha_collections[letter].each do |document| %>
          <article class='al-document-title-bar document'>
            <div class='row'>
              <div class='col-md-12'>
                <h3 class="h5">
                  <%= blacklight_icon :collection, classes: 'al-repository-content-icon' %>
                  <%= link_to document._source["title_filing_ssi"], solr_document_path(document.id) %>
                <small><%= document.normalized_date %></small></h3>
                <% unless @repository.slug == "all" %>
                  <%= content_tag('div', class: 'al-document-abstract-or-scope') do %>
                    <%= content_tag('div', 'data-arclight-truncate' => true) do %>
                      <%= strip_tags(document.abstract_or_scope) %>
                    <% end %>
                  <% end if document.abstract_or_scope %>
                <% end %>
              </div>
            </div>
          </article>
        <% end %>
      </div>
    <% end %>
	 <% end %>	

        </div>
    </div>
  </div>

  <div class="col-md-12 col-lg-4 last_updated">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title h5">Last Updated</h2>
        <% @last_collections.each do |document| %>
          <div class="col-md-12">
            <div class='al-document-title-bar'>
              <div class='row'>
                <article class='document updated_collection col-md-12'>
                  <h3 class="h5"><%= blacklight_icon :collection, classes: 'al-repository-content-icon' %> <%= link_to document.normalized_title, solr_document_path(document.id) %></h3>
                  <%= content_tag('div', class: 'al-document-abstract-or-scope') do %>
                    <%= content_tag('div', 'data-arclight-truncate' => true) do %>
                      <%= strip_tags(document.abstract_or_scope) %>
                    <% end %>
                  <% end if document.abstract_or_scope %>
                </article>
              </div>
            </div>
          </div>
        <% end %>
        <div class="col text-right all-link">
          <span class="al-repository-collections">
            <% if @repository.slug == "sub" || @repository.slug == "all" %>
              <%= link_to(t(:'arclight.views.repositories.view_all_collections'), all_collections_path(@repository), class: "card-link") %>
            <% else %>
              <%= link_to(t(:'arclight.views.repositories.view_all_collections'), collecting_area_path(@repository), class: "card-link") %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>